version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@3

jobs:
  setup:
    docker:
      - image: cimg/node:12.22.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - .
  build:
    docker:
      - image: cimg/node:12.22.1
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Build
          command: npm run only:build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  lint:
    docker:
      - image: cimg/node:12.22.1
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: check format
          command: npm run format:check
      - run:
          name: Lint
          command: npm run eslint:check -- --format junit --output-file ./reports/eslint/results.xml
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  test:
    docker:
      - image: cimg/node:12.22.1
    environment:
      MOCHA_OPTS: --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/junit/mocha/mocha.xml
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Unit Tests
          command: npm run only:test
      - run:
          name: Coverage
          command: npm run only:lCov
      - sixrs-gke/codecov
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  publish:
    docker:
      - image: cimg/node:12.22.1
    steps:
      - attach_workspace:
          at: ./
      - sixrs-gke/run-release
      - sixrs-gke/npm-public-publish
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - setup
      - build:
          context: 6rs-public-npm
          requires:
            - setup
      - lint:
          context: 6rs-public-npm
          requires:
            - setup
      - test:
          context: 6rs-public-npm
          requires:
            - build
      - publish:
          context: 6rs-public-npm
          requires:
            - setup
            - build
            - lint
            - test
          filters:
            branches:
              only:
                - main
                - /^hotfix\/.*
